// src/TaskList/TaskList.tsx
import { invoke } from "@tauri-apps/api";
import { For, onMount } from "solid-js";

import { useTaskList } from "../contexts/TaskListContext";

import Task from "./Task";

function TaskList() {
  const [taskList, { refreshTaskList }] = useTaskList();

  onMount(async () => {
    refreshTaskList(await invoke("get_tasks"));
  });

  return (
    <div class="list-group">
      <For each={taskList}>{(task) => <Task done={task.done} contents={task.contents} starred={task.starred} />}</For>
    </div>
  );
}

export default TaskList;

// src/lib/components/TaskList.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	import { invoke } from '@tauri-apps/api/core';

	import Task from './Task.svelte';

	let tasks: Task[];

	onMount(async () => {
		tasks = await invoke('get_tasks', {});
	});
</script>

{#if tasks}
	<ul
		class="w-full bg-white rounded-lg border border-gray-200 dark:bg-gray-800 dark:border-gray-600 divide-y divide-gray-200 dark:divide-gray-600"
	>
		{#each tasks as task}
			<li><Task contents={task.contents} done={task.done} taskId={task.id} /></li>
		{/each}
	</ul>
{/if}
